#: requires jetstack/cert-manager 0.5.2 installed
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: example-letsencrypt-production
  namespace: example
spec:
  acme:
    # The ACME server URL
    server: "https://acme-v02.api.letsencrypt.org/directory"
    # Email address used for ACME registration
    email: "tarvitz@blacklibrary.ru"

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production

    # Enable the HTTP-01 challenge provider
    http01: {}
